export const blogPosts = [
  {
    slug: "foundation-1-the-north-star-why-direction-drives-growth",
    title: "Foundation #1: The North Star — Why Direction Drives Growth",
    description:
      "Without a shared destination, teams optimize locally instead of moving collectively. Here’s how to create real strategic alignment.",
    thumbnail:
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80",
    readTime: "5 min read",
    category: "Strategy",
    publishedAt: "March 14, 2026",
    publishedBy: "Cam Lillico",
    body: [
      "A founder told me, \"We\u2019re busy all day, but I can\u2019t tell if we\u2019re actually winning.\" If you\u2019ve ever had that feeling, you\u2019re not broken. You\u2019re likely running without a true North Star.",
      "Most leadership teams don\u2019t lack effort. They lack shared direction. Sales pushes for quick wins, operations protects margin, marketing chases reach, and product fights for roadmap capacity. Everyone is competent. Everyone is committed. And everyone is pulling a slightly different way.",
      "A North Star is not a slogan. It is a decision system. In practical terms, it includes six things: your core values, your purpose, your strategic direction, your long-term vision, your ideal customer, and your non-negotiable way of operating.",
      "When those six are clear, decisions speed up. Teams stop escalating every choice to the founder. Middle managers make better calls. Hiring gets easier because fit is easier to assess. Priorities become less emotional and more objective.",
      "When those six are fuzzy, the opposite happens. You get polite misalignment. People nod in meetings, then execute different plans. You get activity without traction. You get recurring debate about the same issues because no one has a common filter for trade-offs.",
      "A subtle BOS360 principle I come back to is this: clarity before intensity. You can\u2019t outwork strategic confusion. You can only expose it faster.",
      "Let\u2019s compare two companies at roughly the same size. Company A says, \"We serve everyone, we\u2019re open to any opportunity, and we\u2019ll figure it out quarter to quarter.\" Company B can clearly state: who they serve, what problems they solve best, what they will not do, and what the next three years should look like.",
      "Company A looks flexible. Company B looks focused. Twelve months later, Company B usually has better margins, fewer internal battles, stronger team confidence, and cleaner execution. Not because they had better people\u2014because they had better alignment.",
      "If you\u2019re a founder, this is where your leadership job gets real. Your team needs to hear direction repeatedly, not once. Strategic clarity has to show up in hiring decisions, quarterly priorities, weekly dashboards, and meeting language.",
      "Here is a practical way to build your North Star: start with behavior-based core values (how we operate when no one is watching). Define your ideal customer in plain language. Write your 3-year picture in concrete terms. Then convert that vision into annual and quarterly priorities.",
      "Once drafted, pressure-test it with your leadership team. Ask: where are we still vague? What would two smart leaders disagree on right now? Where are we pretending to be aligned? Those questions surface ambiguity fast.",
      "Then communicate it like your company depends on it\u2014because it does. Repeat the same core messages in all-hands meetings, leadership sessions, 1:1s, and planning reviews. Repetition is not overcommunication. Repetition is alignment.",
      "Actionable takeaways:\n1) Define 3\u20135 behavior-based core values with examples.\n2) Clarify your ideal customer and who you are not for.\n3) Write a specific 3-year vision with measurable outcomes.\n4) Translate vision into quarterly priorities with owners.\n5) Repeat direction weekly until your team can say it without you.",
      "Direction creates confidence. Confidence creates speed. And speed, pointed in the right direction, is one of the biggest advantages a growing company can build.",
    ],
  },
  {
    slug: "foundation-2-discipline-beats-inspiration",
    title: "Foundation #2: Discipline Beats Inspiration",
    description:
      "Most plans fail from weak execution rhythm, not weak ideas. Build the metric and accountability system that compounds results.",
    thumbnail:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80",
    readTime: "4–5 min read",
    category: "Execution",
    publishedAt: "March 15, 2026",
    publishedBy: "Cam Lillico",
    body: [
      "Inspiration is great for kickoff meetings. Discipline is what gets you to December.",
      "I\u2019ve watched leadership teams leave planning sessions energized, clear, and fully committed\u2014then lose momentum by week five. Not because they got lazy. Because they didn\u2019t build a weekly execution rhythm strong enough to carry the plan.",
      "If you want traction, execution has three core elements: clear goals, leading indicators, and accountability rhythms.",
      "Clear goals mean less than five true priorities for the quarter, each with a single owner. If everything is a priority, nothing is. If everyone owns it, no one owns it.",
      "Leading indicators are the metrics that show smoke before the fire. Revenue is a lagging outcome. Pipeline quality, meetings booked, proposal velocity, retention trends, and hiring pipeline health tell you what is coming next.",
      "A simple example: most teams discover a June revenue miss in June. Disciplined teams can usually see it in April by watching pipeline conversion and deal movement by stage. That time window is the difference between correction and excuse-making.",
      "The third element is accountability rhythm. Weekly review. Same day, same time, same scorecard. Not a status theater. A decision forum.",
      "In founder-led companies, this is where drift often starts. The founder keeps adding goals mid-quarter, leaders protect their own lanes, and meetings become updates instead of commitments. The fix is boring\u2014and powerful: simplify, assign ownership, and review every week.",
      "A subtle BOS360 pattern worth noting: teams improve fastest when they treat metrics as learning tools, not weapons. Scorecards should expose reality, not shame people.",
      "Use quarterly priorities to force focus. Use weekly metrics to protect progress. Use accountability to close the gap between intention and execution.",
      "Actionable takeaways:\n1) Pick 5\u201310 weekly leading indicators that predict your quarter.\n2) Assign one accountable owner per goal.\n3) Run a weekly scorecard review with real decisions, not commentary.\n4) Keep quarterly priorities limited and visible.\n5) Cut one low-value initiative this week to protect focus.",
      "Discipline feels rigid at first. Then it becomes momentum. And momentum is what turns a good strategy into real, repeatable growth.",
    ],
  },
  {
    slug: "foundation-3-systems-create-speed",
    title: "Foundation #3: Systems Create Speed",
    description:
      "Founders often resist structure because they fear bureaucracy. In reality, systems are what make scale possible.",
    thumbnail:
      "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80",
    readTime: "4 min read",
    category: "Leadership",
    publishedAt: "March 16, 2026",
    publishedBy: "Cam Lillico",
    body: [
      "Founders often tell me, \"I don\u2019t want process to slow us down.\" I get it. Nobody starts a company to build bureaucracy. But there\u2019s a difference between bureaucracy and structure.",
      "In the early stage, speed comes from instinct. At scale, speed comes from clarity. Once a company grows, undocumented decisions become expensive. Work gets redone. Priorities conflict. New hires guess at standards. Meetings multiply because nobody trusts the system.",
      "Good systems don\u2019t kill momentum. They protect it. They create alignment, repeatability, and accountability so teams can move faster with fewer surprises.",
      "I worked with one leadership team that prided itself on being agile. In reality, the same operational fires kept returning every month. Why? Core cross-functional processes were living in people\u2019s heads, not in shared workflows.",
      "After we documented key processes, clarified decision rights, and tightened the leadership cadence, they didn\u2019t become slower. They became calmer and faster. Less heroics. More consistent execution.",
      "That\u2019s the real trade-off: chaos can feel fast in the moment, but it is slow over time. Systems can feel slower in the setup, but they are dramatically faster over a year.",
      "Another founder concern is that process reduces creativity. In practice, the opposite is true. When routine execution is structured, creative energy is freed for strategic work.",
      "A practical BOS360 lens is to separate strategic thinking from execution rhythm. Strategy sets direction. System cadence turns direction into weekly behavior.",
      "Actionable takeaways:\n1) Document your most critical recurring processes.\n2) Define quarterly priorities with explicit owners and due dates.\n3) Run consistent leadership meetings with a clear agenda.\n4) Review strategy annually and stress-test assumptions.\n5) Remove one recurring bottleneck by clarifying who decides.",
      "If your business currently feels hard to steer, that is not a talent problem. It is usually a system maturity problem. Fix the operating rhythm, and speed returns\u2014this time with control.",
    ],
  },
  {
    slug: "foundation-4-fast-decisions-win",
    title: "Foundation #4: Fast Decisions Win",
    description:
      "The biggest waste in leadership is delayed commitment. Decision velocity is a real competitive advantage.",
    thumbnail:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
    readTime: "3–4 min read",
    category: "Decision Making",
    publishedAt: "March 17, 2026",
    publishedBy: "Cam Lillico",
    body: [
      "Most companies don\u2019t lose because they made one bad decision. They lose because they delayed ten obvious ones.",
      "Leadership teams often frame delay as caution. Sometimes it is. But more often it is fear: fear of being wrong, fear of conflict, fear of disappointing people, fear of choosing before perfect certainty.",
      "Decision speed is a real competitive advantage. Fast-deciding teams learn faster, adapt faster, and compound execution while others are still debating.",
      "A simple framework helps. Put decisions into three buckets: reversible, important, and strategic one-way-door decisions. Most day-to-day business choices are reversible. They should move quickly.",
      "Important decisions deserve stronger debate and better data, but they still need deadlines. Strategic one-way-door decisions require deep thinking, but they are fewer than leaders assume.",
      "A common failure pattern is treating reversible decisions like strategic ones. Teams over-analyze, defer ownership, and quietly burn weeks.",
      "One founder I coached had a stuck hiring decision for six weeks. Team morale dropped, deliverables slipped, and everyone felt it. The decision itself wasn\u2019t hard\u2014the emotional cost of making it was.",
      "Use this rule: debate hard, decide clearly, align publicly. Once committed, stop relitigating and execute.",
      "Actionable takeaways:\n1) Define decision owners by function and by threshold.\n2) Add a clear decision-by date for every major issue.\n3) Label decisions as reversible vs strategic before debating.\n4) Separate open debate from post-decision commitment.\n5) Move with 70% information when downside is manageable.",
      "Perfection is usually too expensive. Decisive leadership, paired with learning, is how teams build real momentum.",
    ],
  },
  {
    slug: "foundation-5-leadership-lessons-learned-hard-way",
    title: "Foundation #5: Leadership Lessons I Learned the Hard Way",
    description:
      "The most durable leadership principles are learned through mistakes, not theory. Here are the ones that changed my operating approach.",
    thumbnail:
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80",
    readTime: "4–5 min read",
    category: "Leadership",
    publishedAt: "March 18, 2026",
    publishedBy: "Cam Lillico",
    body: [
      "Most leadership principles I trust now were not learned from a podcast. They were learned by getting something wrong in the real world.",
      "Early on, I believed intelligence and intensity could solve almost anything. Over time, I learned that clarity and consistency outperform brilliance in most operating environments.",
      "Here are ten lessons I learned the hard way, grouped by what matters most in scaling companies.",
      "Strategy: (1) Clarity beats complexity. If your strategy needs a decoder ring, your team won\u2019t execute it. (2) Focus is a growth lever. Every yes to one initiative is a no to ten others. (3) Strategy must survive contact with weekly reality.",
      "People: (4) Right people in the right roles beats almost every tactical advantage. (5) Delayed people decisions are expensive. The team already feels the drag before you act.",
      "Communication: (6) Repetition is leadership, not redundancy. If you\u2019re tired of saying it, people are just starting to hear it. (7) Ambiguous language creates avoidable conflict.",
      "Execution: (8) Ownership must be singular. Shared accountability sounds collaborative and behaves like diffusion. (9) Cadence creates confidence. Teams trust leaders who show up consistently in how they review, decide, and follow through.",
      "Culture: (10) Culture reflects tolerated behavior, not stated values. What leaders permit becomes the norm.",
      "My clearest leadership failure was delaying a role-fit call because I wanted to avoid discomfort. The individual was talented, but not in the right seat. I waited too long, and the cost was broader team friction and avoidable execution drag.",
      "The lesson was direct: kindness is not delay. Real leadership is timely clarity\u2014with respect, honesty, and accountability.",
      "A subtle BOS360 thread in all of this is operational honesty. Name reality early. Build structure around it. Then execute with discipline.",
      "Actionable takeaways:\n1) Identify one people decision you are delaying and set a date.\n2) Clarify one ambiguous owner this week.\n3) Repeat top priorities in every leadership meeting.\n4) Remove one initiative that is diluting focus.\n5) Audit tolerated behavior vs stated values.",
      "Leadership is less about having all the answers and more about building conditions where good decisions happen repeatedly.",
    ],
  },
  {
    slug: "foundation-6-the-attitude-to-win",
    title: "Foundation #6: The Attitude to Win",
    description:
      "Winning cultures are not accidental. They are a daily leadership output driven by standards, energy, and accountability.",
    thumbnail:
      "https://images.unsplash.com/photo-1551836022-4c4c79ecde51?auto=format&fit=crop&w=1200&q=80",
    readTime: "3–4 min read",
    category: "Culture",
    publishedAt: "March 19, 2026",
    publishedBy: "Cam Lillico",
    body: [
      "Teams don\u2019t rise to motivational speeches. They rise to daily standards.",
      "In growth-stage companies, leadership attitude quietly shapes everything: urgency, ownership, resilience, and trust. The tone at the top doesn\u2019t stay at the top.",
      "High-performing leaders usually share four behaviors: they bring energy, own outcomes, stay constructively optimistic, and recover quickly when things break.",
      "This is not personality theater. It is operational behavior. Teams watch how leaders handle pressure, setbacks, and ambiguity. Then they mirror it.",
      "The ripple is simple: Leader behavior \u2192 Team behavior \u2192 Culture norms \u2192 Business results.",
      "I watched one leadership group change outcomes without changing strategy. They clarified standards, tightened follow-through, and stopped tolerating avoidable drift. Within one quarter, execution quality improved and internal friction dropped.",
      "Winning attitude is not pretending everything is fine. It is facing reality quickly, responding with ownership, and moving forward with discipline.",
      "A subtle BOS360 habit that helps: close each leadership meeting with explicit commitments and visible owners. Attitude becomes concrete when commitments are clear.",
      "Actionable takeaways:\n1) Model the behavior you expect under pressure.\n2) Set clear non-negotiable standards for execution.\n3) Celebrate real wins to reinforce desired behavior.\n4) Address drift early before it becomes culture.\n5) Protect your own leadership energy\u2014it sets the pace.",
      "Your team doesn\u2019t just hear your standards. They feel them.",
    ],
  },
  {
    slug: "foundation-7-why-leaders-avoid-big-decisions",
    title: "Foundation #7: Why Leaders Avoid Big Decisions",
    description:
      "Most delayed decisions are emotional, not analytical. Naming the fear helps restore decision quality.",
    thumbnail:
      "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&q=80",
    readTime: "3 min read",
    category: "Leadership",
    publishedAt: "March 20, 2026",
    publishedBy: "Cam Lillico",
    body: [
      "Big decisions are rarely blocked by missing data. They\u2019re usually blocked by human fear.",
      "Leaders avoid hard calls for predictable reasons: fear of failure, fear of conflict, fear of hurting relationships, and fear of being the one who got it wrong.",
      "The problem is delay feels safer than action in the moment, but it creates larger costs over time\u2014confusion, slower execution, quieter frustration, and avoidable risk.",
      "I\u2019ve seen this most often in role-fit decisions, strategy pivots, and pricing moves. Everyone can sense the issue, but the team keeps gathering \"one more input\" to postpone commitment.",
      "A practical way through hesitation is to ask three questions:\n1) What happens if we wait?\n2) What happens if we act?\n3) What advice would we give another CEO in this exact situation?",
      "Those questions break emotional fog and force clearer trade-offs.",
      "Another useful move: separate irreversible consequences from temporary discomfort. Most hesitation is about discomfort, not existential risk.",
      "Actionable takeaways:\n1) Name the real fear out loud in the leadership room.\n2) Put the decision on a deadline.\n3) Define the downside of delay, not just the downside of action.\n4) Commit, communicate clearly, and execute.",
      "Decisive leadership isn\u2019t fearless. It\u2019s acting responsibly even when certainty is incomplete.",
    ],
  },
  {
    slug: "foundation-8-strong-leadership-includes-vulnerability",
    title: "Foundation #8: Strong Leadership Includes Vulnerability",
    description:
      "The best leaders are not performatively perfect. They are self-aware, coachable, and willing to own mistakes early.",
    thumbnail:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
    readTime: "2–3 min read",
    category: "Leadership Health",
    publishedAt: "March 21, 2026",
    publishedBy: "Cam Lillico",
    body: [
      "Many leaders still believe credibility means always looking certain. In real organizations, that posture eventually breaks trust.",
      "Strong leadership includes vulnerability\u2014not performative vulnerability, but practical vulnerability: self-awareness, humility, openness to feedback, and a willingness to own mistakes early.",
      "When leaders admit what they missed and what they\u2019re changing, teams usually trust them more, not less. Clarity plus accountability is persuasive.",
      "I\u2019ve seen leadership meetings transform when a founder starts with, \"Here\u2019s what I got wrong last quarter and what we\u2019re doing differently.\" It lowers defensiveness and raises problem-solving quality.",
      "Vulnerability is not weakness. It is an operating choice that improves learning speed.",
      "In founder-led environments, this matters even more. If the top of the house is unapproachable, issues surface late. If the top is honest and coachable, issues surface early.",
      "A subtle BOS360 advantage is building feedback into cadence so learning is not accidental.",
      "Actionable takeaways:\n1) Ask for direct feedback from your leadership team each quarter.\n2) Acknowledge mistakes before they become narratives.\n3) Model learning behavior publicly.\n4) Reward candor and intelligent dissent.",
      "The strongest leaders are not the ones who pretend to have no blind spots. They\u2019re the ones who reduce blind spots fastest.",
    ],
  },
  {
    slug: "foundation-9-no-one-has-it-figured-out",
    title: "Foundation #9: No One Has It Figured Out",
    description:
      "Entrepreneurship is uncertainty management. The winners are usually the teams that learn faster, not the teams that guess perfectly.",
    thumbnail:
      "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80",
    readTime: "2 min read",
    category: "Founder Mindset",
    publishedAt: "March 22, 2026",
    publishedBy: "Cam Lillico",
    body: [
      "If you feel like everyone else has a cleaner playbook than you do, welcome to entrepreneurship.",
      "Behind polished updates, most companies are wrestling with uncertainty: hiring misses, positioning tension, operational bottlenecks, and shifting priorities.",
      "There is no universal script for building a great company. There are principles, patterns, and trade-offs\u2014and a lot of iteration.",
      "The teams that win are usually not the teams that guessed perfectly in Q1. They are the teams that learned quickly, adjusted honestly, and kept execution steady.",
      "I worked with one founder who changed go-to-market direction three times before finding durable traction. What worked wasn\u2019t luck. It was disciplined learning cycles and fast issue resolution.",
      "When leaders normalize uncertainty, teams stay resilient. When leaders pretend certainty, teams get brittle.",
      "Actionable takeaways:\n1) Treat uncertainty as normal, not as failure.\n2) Shorten feedback loops on key assumptions.\n3) Fix recurring issues quickly.\n4) Keep your operating cadence stable while strategy evolves.",
      "No one has it all figured out. The goal is not perfection\u2014it\u2019s faster learning with stronger execution.",
    ],
  },
  {
    slug: "foundation-10-your-first-team-is-the-leadership-team",
    title: "Foundation #10: Your First Team Is the Leadership Team",
    description:
      "When executives prioritize departments over the leadership team, alignment breaks. Company performance follows leadership team health.",
    thumbnail:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80",
    readTime: "1 min read",
    category: "Leadership Team",
    publishedAt: "March 23, 2026",
    publishedBy: "Cam Lillico",
    body: [
      "Your first team is not your department. It is your leadership team.",
      "When executives prioritize functional loyalty over enterprise outcomes, silos become inevitable. Alignment drops. Politics rises. Results follow.",
      "The classic dysfunction pattern is still useful: absence of trust, fear of conflict, lack of commitment, avoidance of accountability, and inattention to results.",
      "Trust is the foundation. Without trust, conflict becomes personal or avoided. Without healthy conflict, commitment stays shallow. Without commitment, accountability becomes selective.",
      "Strong leadership teams debate openly, commit collectively, and hold each other accountable to company-level outcomes\u2014not local wins.",
      "In practice, this means deciding in the room, aligning in public, and executing as one team.",
      "Actionable takeaways:\n1) Re-state first-team expectations explicitly.\n2) Encourage real debate before decisions.\n3) Commit together once direction is set.\n4) Hold peers accountable across functions.\n5) Put company results above departmental preferences.",
      "If the leadership team is aligned, the business can absorb almost any challenge. If it isn\u2019t, even strong strategy will underperform.",
    ],
  },
];

export function getPostBySlug(slug) {
  return blogPosts.find((post) => post.slug === slug);
}
